// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;

[Table(name: "BeneFactorNotes", Schema = "web")]
public partial class BeneFactorNote
{
    public int Id { get; set; }

    public int BeneFactorId { get; set; }

    public string Note { get; set; }

    public string Suggestion { get; set; }

    public DateTime? InsertDate { get; set; }

    public virtual BeneFactor BeneFactor { get; set; }
}