// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;

[Table(name: "BeneFactors", Schema = "web")]
public partial class BeneFactor : AuditableEntity
{
    public int Id { get; set; }

    public int Code { get; set; }

    public string FullName { get; set; }

    public string Description { get; set; }

    public string Phone { get; set; }

    public string Phone2 { get; set; }

    public string Address { get; set; }

    public string FaceBook { get; set; }

    public string Image { get; set; }

    public int NationalityId { get; set; }

    public string WelcomeMessage { get; set; }

    public ICollection<BeneFactorDetail> BeneFactorDetails { get; set; } = new List<BeneFactorDetail>();

    public ICollection<BeneFactorNote> BeneFactorNotes { get; set; } = new List<BeneFactorNote>();

    public BeneFactorNationality Nationality { get; set; }
}