// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "EventSliderImages", Schema = "web")]
public partial class EventSliderImage
{
    public int Id { get; set; }

    public int EventId { get; set; }

    public string Image { get; set; }

    public int DisplayOrder { get; set; }

    public Event Event { get; set; }
}