// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyStatus", Schema = "admin")]
public partial class FamilyStatus : AuditableEntity
{
    public int Id { get; set; }
    public int StatusTypeId { get; set; }
    public int NationalityId { get; set; }
    public int Code { get; set; }
    public string Name { get; set; }
    public string Fname { get; set; }
    public string Address { get; set; }
    public string Village { get; set; }
    public string Center { get; set; }
    public string Governorate { get; set; }
    public string Phone { get; set; }
    public string Phone1 { get; set; }
    public string SupportingParty { get; set; }
    public string ReasonOfRefuse { get; set; }
    public int CategoryId { get; set; }
    public DateTime AddedDate { get; set; }
    public string NationalId { get; set; }
    public int? Age { get; set; }
    public string Education { get; set; }
    public string Jop { get; set; }
    public string MaritalStatus { get; set; }
    public string Relevance { get; set; }
    public virtual FamilyCategory Category { get; set; }
    public virtual ICollection<FamilyDetail> FamilyDetails { get; set; } = new List<FamilyDetail>();
    public virtual ICollection<FamilyExpense> FamilyExpenses { get; set; } = new List<FamilyExpense>();
    public virtual ICollection<FamilyExtraDetail> FamilyExtraDetails { get; set; } = new List<FamilyExtraDetail>();
    public virtual ICollection<FamilyIncome> FamilyIncomes { get; set; } = new List<FamilyIncome>();
    public virtual ICollection<FamilyNeed> FamilyNeeds { get; set; } = new List<FamilyNeed>();
    public virtual ICollection<FamilyPatient> FamilyPatients { get; set; } = new List<FamilyPatient>();
    public virtual FamilyNationality Nationality { get; set; }
    public virtual FamilyStatusType StatusType { get; set; }
}