// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyNeedTypes", Schema = "admin")]
public partial class FamilyNeedType : AuditableEntity
{
    public int Id { get; set; }
    public string Name { get; set; }

    public int CategoryId { get; set; }

    public virtual FamilyNeedCategory Category { get; set; }

    public virtual ICollection<FamilyNeed> FamilyNeeds { get; set; } = new List<FamilyNeed>();
}