// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyExtraDetails", Schema = "admin")]
public partial class FamilyExtraDetail
{
    public int Id { get; set; }

    public int FamilyStatusId { get; set; }

    public string StatusDescription { get; set; }

    public string HousingNeedsAndStatus { get; set; }

    public string ResearcherNotes { get; set; }

    public string ReferencesNotes { get; set; }

    public DateTime? LastVisitDate { get; set; }

    public string PersonalPapers { get; set; }

    public virtual FamilyStatus FamilyStatus { get; set; }
}