// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;

[Table(name: "FamilyStatusTypes", Schema = "admin")]
public partial class FamilyStatusType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<FamilyStatus> FamilyStatuses { get; set; } = new List<FamilyStatus>();
}