// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;

[Table(name: "FamilyDetails", Schema = "admin")]
public partial class FamilyDetail
{
    public int Id { get; set; }

    public int FamilyStatusId { get; set; }

    public string Name { get; set; }

    public string Relevance { get; set; }

    public int? Age { get; set; }

    public string MaritalStatus { get; set; }

    public string Education { get; set; }

    public string Jop { get; set; }

    public string NationalId { get; set; }

    public int? ChildernsCount { get; set; }

    public int? FamilyMembersCount { get; set; }

    public virtual FamilyStatus FamilyStatus { get; set; }
}