// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "GeneralTasks", Schema = "admin")]
public partial class GeneralTask : AuditableEntity
{
    public int Id { get; set; }

    public int StatusId { get; set; }

    public string Task { get; set; }

    public string AssignTo { get; set; }

    public DateTime TaskAddedDate { get; set; }

    public virtual TaskStatus Status { get; set; }
}