// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "PhotoDetails", Schema = "web")]
public partial class PhotoDetail
{
    public int Id { get; set; }

    public int PhotoId { get; set; }

    public string Image { get; set; }

    public int DisplayOrder { get; set; }

    public virtual Photo Photo { get; set; }
}