// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "Photos", Schema = "web")]
public partial class Photo : AuditableEntity
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public bool IsVisible { get; set; }

    public virtual ICollection<PhotoDetail> PhotoDetails { get; set; } = new List<PhotoDetail>();
}