// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "Projects", Schema = "web")]
public partial class Project : AuditableEntity
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string TotalDonationAmount { get; set; }

    public string BenefactorCount { get; set; }

    public string TotalAmount { get; set; }

    public string RemainingAmount { get; set; }

    public bool IsVisible { get; set; }

    public string ProjectUrl { get; set; }

    public virtual ICollection<ProjectDetail> ProjectDetails { get; set; } = new List<ProjectDetail>();
}