// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "WebSiteVisitors", Schema = "web")]
public partial class WebSiteVisitor
{
    public int Id { get; set; }

    public string SessionId { get; set; }

    public DateTime InsertDate { get; set; }
}