// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using ZayirAlkhayr.Entities.Auth;
using ZayirAlkhayr.Entities.Models.School;
using ZayirAlkhayr.Entities.Models.Settings;

namespace ZayirAlkhayr.Entities.Models;

public partial class ZADbContext : IdentityDbContext<AdminUser>
{
    public ZADbContext(DbContextOptions<ZADbContext> options)
        : base(options)
    {
    }

    #region ZAInstitution
    public virtual DbSet<FinancialTransaction> FinancialTransactions { get; set; }
    public virtual DbSet<ActivitiesSliderImage> ActivitiesSliderImage { get; set; }
    public virtual DbSet<Activity> Activities { get; set; }
    public virtual DbSet<BeneFactor> BeneFactors { get; set; }
    public virtual DbSet<BeneFactorDetail> BeneFactorDetails { get; set; }
    public virtual DbSet<BeneFactorNationality> BeneFactorNationalities { get; set; }
    public virtual DbSet<BeneFactorNote> BeneFactorNotes { get; set; }
    public virtual DbSet<BeneFactorType> BeneFactorTypes { get; set; }
    public virtual DbSet<Event> Events { get; set; }
    public virtual DbSet<EventSliderImage> EventSliderImages { get; set; }
    public virtual DbSet<FamilyCategory> FamilyCategories { get; set; }
    public virtual DbSet<FamilyDetail> FamilyDetails { get; set; }
    public virtual DbSet<FamilyExpense> FamilyExpenses { get; set; }
    public virtual DbSet<FamilyExtraDetail> FamilyExtraDetails { get; set; }
    public virtual DbSet<FamilyIncome> FamilyIncomes { get; set; }
    public virtual DbSet<FamilyNationality> FamilyNationalities { get; set; }
    public virtual DbSet<FamilyNeed> FamilyNeeds { get; set; }
    public virtual DbSet<FamilyNeedCategory> FamilyNeedCategories { get; set; }
    public virtual DbSet<FamilyNeedType> FamilyNeedTypes { get; set; }
    public virtual DbSet<FamilyPatient> FamilyPatients { get; set; }
    public virtual DbSet<FamilyPatientType> FamilyPatientTypes { get; set; }
    public virtual DbSet<FamilyStatus> FamilyStatuses { get; set; }
    public virtual DbSet<FamilyStatusType> FamilyStatusTypes { get; set; }
    public virtual DbSet<GeneralTask> GeneralTasks { get; set; }
    public virtual DbSet<Orphan> Orphans { get; set; }
    public virtual DbSet<PagesAutoSearch> PagesAutoSearches { get; set; }
    public virtual DbSet<Photo> Photos { get; set; }
    public virtual DbSet<PhotoDetail> PhotoDetails { get; set; }
    public virtual DbSet<Project> Projects { get; set; }
    public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
    public virtual DbSet<SliderImage> SliderImages { get; set; }
    public virtual DbSet<TaskStatus> TaskStatuses { get; set; }
    public virtual DbSet<WebSiteVisitor> WebSiteVisitors { get; set; }
    #endregion

    #region Settings
    public virtual DbSet<Application> Applications { get; set; }
    public virtual DbSet<PagePermission> PagePermission { get; set; }

    #endregion

    #region School
    public virtual DbSet<Student> Students { get; set; }
    public virtual DbSet<StudentNationality> StudentNationalities { get; set; }
    public virtual DbSet<AcademicStage> AcademicStages { get; set; }
    public virtual DbSet<DiscountType> DiscountTypes { get; set; }
    public virtual DbSet<Parent> Parents { get; set; }
    public virtual DbSet<AcademicYear> AcademicYears { get; set; }
    public virtual DbSet<FeeTemplate> FeeTemplates { get; set; }
    public virtual DbSet<StudentEnrollment> StudentEnrollments { get; set; }
    public virtual DbSet<StudentFee> StudentFees { get; set; }
    public virtual DbSet<StudentPayment> StudentPayments { get; set; }
    public virtual DbSet<FeeType> FeeTypes { get; set; }
    public virtual DbSet<StudentType> StudentTypes { get; set; }
    

    #endregion


}