// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using ZayirAlkhayr.Entities.Auth;

namespace ZayirAlkhayr.Entities.Models;

public partial class ZADbContext : IdentityDbContext<AdminUser>
{
    public ZADbContext(DbContextOptions<ZADbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AccountsExportMony> AccountsExportMony { get; set; }
    public virtual DbSet<AccountsImportMony> AccountsImportMony { get; set; }
    public virtual DbSet<ActivitiesSliderImage> ActivitiesSliderImage { get; set; }
    public virtual DbSet<Activity> Activities { get; set; }
    public virtual DbSet<BeneFactor> BeneFactors { get; set; }
    public virtual DbSet<BeneFactorDetail> BeneFactorDetails { get; set; }
    public virtual DbSet<BeneFactorNationality> BeneFactorNationalities { get; set; }
    public virtual DbSet<BeneFactorNote> BeneFactorNotes { get; set; }
    public virtual DbSet<BeneFactorType> BeneFactorTypes { get; set; }
    public virtual DbSet<Event> Events { get; set; }
    public virtual DbSet<EventSliderImage> EventSliderImages { get; set; }
    public virtual DbSet<FamilyCategory> FamilyCategories { get; set; }
    public virtual DbSet<FamilyDetail> FamilyDetails { get; set; }
    public virtual DbSet<FamilyExpense> FamilyExpenses { get; set; }
    public virtual DbSet<FamilyExtraDetail> FamilyExtraDetails { get; set; }
    public virtual DbSet<FamilyIncome> FamilyIncomes { get; set; }
    public virtual DbSet<FamilyNationality> FamilyNationalities { get; set; }
    public virtual DbSet<FamilyNeed> FamilyNeeds { get; set; }
    public virtual DbSet<FamilyNeedCategory> FamilyNeedCategories { get; set; }
    public virtual DbSet<FamilyNeedType> FamilyNeedTypes { get; set; }
    public virtual DbSet<FamilyPatient> FamilyPatients { get; set; }
    public virtual DbSet<FamilyPatientType> FamilyPatientTypes { get; set; }
    public virtual DbSet<FamilyStatus> FamilyStatuses { get; set; }
    public virtual DbSet<FamilyStatusType> FamilyStatusTypes { get; set; }
    public virtual DbSet<GeneralTask> GeneralTasks { get; set; }
    public virtual DbSet<Orphan> Orphans { get; set; }
    public virtual DbSet<PagesAutoSearch> PagesAutoSearches { get; set; }
    public virtual DbSet<Photo> Photos { get; set; }
    public virtual DbSet<PhotoDetail> PhotoDetails { get; set; }
    public virtual DbSet<Project> Projects { get; set; }
    public virtual DbSet<ProjectDetail> ProjectDetails { get; set; }
    public virtual DbSet<SliderImage> SliderImages { get; set; }
    public virtual DbSet<TaskStatus> TaskStatuses { get; set; }
    public virtual DbSet<WebSiteVisitor> WebSiteVisitors { get; set; }
}