// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;

[Table(name: "AccountsExportMony", Schema = "admin")]
public partial class AccountsExportMony: AuditableEntity
{
    public int Id { get; set; }

    public double TotalValue { get; set; }

    public string Details { get; set; }

    public int BeneFactorId { get; set; }

    public int BeneFactorTypeId { get; set; }
}