// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "BeneFactorNationalities", Schema = "web")]
public partial class BeneFactorNationality : AuditableEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public ICollection<BeneFactor> BeneFactors { get; set; } = new List<BeneFactor>();
}