// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "BeneFactorDetails", Schema = "institution")]
public partial class BeneFactorDetail : AuditableEntity
{
    public int Id { get; set; }

    public int? ParentId { get; set; }

    public string Image { get; set; }

    public double? TotalValue { get; set; }

    public DateTime PaymentDate { get; set; }

    public string Details { get; set; }

    public int BeneFactorId { get; set; }

    public int BeneFactorTypeId { get; set; }

    public bool? IsActive { get; set; }

    public bool? IsParent { get; set; }
    [NotMapped]
    public string OldFileName { get; set; }
    [NotMapped]
    public bool IsFinalSubscribe { get; set; }
    [NotMapped]
    public IFormFile Files { get; set; }
    [NotMapped]
    public string PaymentDateStr { get; set; }

    public BeneFactor BeneFactor { get; set; }

    public BeneFactorType BeneFactorType { get; set; }
}