// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "Events", Schema = "web")]
public partial class Event : AuditableEntity
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public bool IsVisible { get; set; }

    public DateTime? FromDate { get; set; }

    public DateTime? ToDate { get; set; }

    public string Month { get; set; }

    [NotMapped]
    public List<string> Images { get; set; }
    [NotMapped]
    public string FromDateStr { get; set; }
    [NotMapped]
    public string ToDateStr { get; set; }

    public ICollection<EventSliderImage> EventSliderImages { get; set; } = new List<EventSliderImage>();
}