// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyPatient", Schema = "admin")]
public partial class FamilyPatient
{
    public int Id { get; set; }

    public int FamilyStatusId { get; set; }

    public string Name { get; set; }

    public string PatientDate { get; set; }

    public string Specialization { get; set; }

    public bool? IsMedicalReport { get; set; }

    public bool? IsNeedProcess { get; set; }

    public int PatientTypeId { get; set; }

    public FamilyStatus FamilyStatus { get; set; }

    public FamilyPatientType PatientType { get; set; }
}