// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyNeeds", Schema = "admin")]
public partial class FamilyNeed
{
    public int Id { get; set; }

    public int StatusId { get; set; }

    public int NeedTypeId { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public bool IsWaiting { get; set; }

    public FamilyNeedType NeedType { get; set; }

    public FamilyStatus Status { get; set; }
}