// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyExpenses", Schema = "admin")]
public partial class FamilyExpense
{
    public int Id { get; set; }

    public int FamilyStatusId { get; set; }

    public int? Rent_Electricity_Water_Gas_Sewage { get; set; }

    public int? MedicalExamination_Treatment { get; set; }

    public int SchoolExpenses { get; set; }

    public int? PhysiotherapySessions { get; set; }

    public int? Analysis { get; set; }

    public int? SatisfactoryTransfers { get; set; }

    public int? MedicalXRays { get; set; }

    public bool? IsMinisterialSupply { get; set; }

    public bool? IsFoodBank { get; set; }

    public int? TotalFamilyExpenses { get; set; }

    public int? NetFamilyIncome { get; set; }

    public int? FamilyCount { get; set; }

    public int? AvgPersonIncome { get; set; }

    public int? Installment_debts { get; set; }

    public FamilyStatus FamilyStatus { get; set; }
}