// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyIncome", Schema = "admin")]
public partial class FamilyIncome
{
    public int Id { get; set; }

    public int FamilyStatusId { get; set; }

    public int? FatherJop { get; set; }

    public int? MotherJop { get; set; }

    public int? ChildernsJop { get; set; }

    public int? AffairSpension_SocialSolidarity { get; set; }

    public int? Project { get; set; }

    public int? LiveStock_Lands { get; set; }

    public int? Organization_ZakatCommittee { get; set; }

    public int? InsurancePension { get; set; }

    public string Comments { get; set; }

    public int Other { get; set; }

    public int? TotalFamilyIncome { get; set; }

    public FamilyStatus FamilyStatus { get; set; }
}