// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "FamilyNeedCategories", Schema = "admin")]
public partial class FamilyNeedCategory : AuditableEntity
{
    public int Id { get; set; }

    public string Name { get; set; }

    public ICollection<FamilyNeedType> FamilyNeedTypes { get; set; } = new List<FamilyNeedType>();
}