// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;

[Table(name: "Orphans", Schema = "admin")]
public partial class Orphan : AuditableEntity
{
    public int Id { get; set; }

    public int FamilyStatusId { get; set; }

    public int? BenefactorId { get; set; }

    public string Name { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string FamilyName { get; set; }

    public string Jop { get; set; }

    public string NationalId { get; set; }

    public string Phone { get; set; }

    public string Address { get; set; }

    public string Income { get; set; }

    public string AcademicStage { get; set; }

    public string FamilyMembersCount { get; set; }

    public string RankingBrothers { get; set; }

    public string HealthStatus { get; set; }

    public string Notes { get; set; }

    public string BenefactorPhone { get; set; }

    public string BenefactorAddress { get; set; }

    public string BenefactorType { get; set; }

    public bool IsGuaranteed { get; set; }

    public int? NationalityId { get; set; }

    public int FamilyDetailsId { get; set; }
}