// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "PagesAutoSearch", Schema = "admin")]
public partial class PagesAutoSearch
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string PageUrl { get; set; }
}