// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "ProjectDetails", Schema = "web")]
public partial class ProjectDetail
{
    public int Id { get; set; }

    public int ProjectId { get; set; }

    public string Image { get; set; }

    public Project Project { get; set; }
}