// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using ZayirAlkhayr.Entities.Common;

namespace ZayirAlkhayr.Entities.Models;


[Table(name: "SliderImages", Schema = "web")]
public partial class SliderImage : AuditableEntity
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Image { get; set; }

    public bool IsVisible { get; set; }
    [NotMapped]
    public string OldFileName { get; set; }
    [NotMapped]
    public IFormFile Files { get; set; }
}